name: daily

permissions:
  contents: write

on:
  schedule:
    - cron: '0 0,12 * * *'   # ogni giorno a 00:00 e 12:00 UTC
  workflow_dispatch:

jobs:
  two-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configura Git
        run: |
          git config user.name "bocaletto-luca"
          git config user.email "${{ secrets.BOCA_EMAIL }}"

      - name: Imposta timestamp
        run: echo "TS=$(date -u +'%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_ENV

      - name: Commit src/test.txt
        run: |
          mkdir -p src
          echo "farm at $TS" > src/test.txt
          git add src/test.txt
          git commit --allow-empty -m "chore: update test.txt at $TS"

      - name: Commit src/test2.txt
        run: |
          echo "farm at $TS" > src/test2.txt
          git add src/test2.txt
          git commit --allow-empty -m "chore: update test2.txt at $TS"

      - name: Push su main
        run: git push origin main
